'''HTML classes for styling'''
widget = 'ui-widget'
widget_head = 'ui-widget-header'
widget_body = 'ui-widget-body'
widget_foot = 'ui-widget-footer'
clickable = 'ui-clickable'
corner_all = 'ui-corner-all'
corner_top = 'ui-corner-top'
corner_bottom = 'ui-corner-bottom'
edit = 'edit'
edit_menu = 'edit-menu'
tabs = 'ui-tabs'
box = 'box'
wrapper = 'wrapper'

object_definition = 'object-definition'