'''HTML classes for styling'''
widget = 'ui-widget'
widget_head = 'ui-widget-header'
widget_body = 'ui-widget-content'
widget_foot = 'ui-widget-footer'
clickable = 'ui-clickable'
corner_all = 'ui-corner-all'
corner_top = 'ui-corner-top'
corner_bottom = 'ui-corner-bottom'
state_default = 'ui-state-default'
state_active = 'ui-state-active'
state_hover = 'ui-state-hover'
edit = 'edit'
edit_menu = 'edit-menu'
tabs = 'ui-tabs'
panel = 'panel'
box = 'box'
wrapper = 'wrapper'
error = 'error'

object_definition = 'object-definition'