from djpcms.html.classes import button_holder, button
form = 'uniForm'
inline = 'inline'
inlineLabels = 'inlineLabels'
inlineLabels2 = 'inlineLabels fullwidth'
inlineLabels3 = 'inlineLabels auto'
blockLabels = 'blockLabels'
inlineFormsets = 'blockLabels2'
nolabel = 'nolabel'
legend = 'legend'
ctrlHolder = 'ctrlHolder'
control = 'control'
required = 'required'
label = 'label'
ui_input = 'ui-input'
align_right = 'align-right'
align_middle = 'align-middle'
layout_block = 'layout-element'